### ISSUE TITLE
Thunderstore 

### ISSUE THREAD

**Issue by pikachukaki** [slyh/Cities2-Various-Mods#17]
Can you put your mod in [Thunderstore ](https://thunderstore.io/c/cities-skylines-ii/) so we can get updates more easiely? Thanks

**Comment by slyh** [comment]
I will release it on Thunderstore if there are no major issues found in the latest update.

**Comment by omayhemo** [comment]
+1

**Comment by ksh971223** [comment]
i want

**Comment by slyh** [comment]
Due to the issues found in v0.2.1, I believe it's inappropriate to release that version on Thunderstore.

I've uploaded [v0.2.2-alpha](https://github.com/slyh/Cities2-Various-Mods/releases/tag/v0.2.2-alpha) and feedback is needed. If deemed stable, this will be the version released on Thunderstore

**Comment by omayhemo** [comment]
Just my view, but ever mod on there is an alpha currently, since there is no official support.  I admire you wanting to get it clean, but it's probably helpful to get the exposure to testers.

**Comment by DomoticaAndrade** [comment]
Is it possible to use this mod and Thunderstore separately?

**Comment by pikachukaki** [comment]
> Is it possible to use this mod and Thunderstore separately?

simply install this mod manually

**Comment by slyh** [comment]
Released on Thunderstore.

All future releases will be categorised as alpha or beta.

Alpha releases represent the latest developments and are essentially untested.

Beta releases usually lag a week behind alphas and will include fixes for bugs discovered in the alpha builds.

However, due to the experimental nature of this project, they should not be considered stable or production-ready.
